applications/claveunica/urls.py
from django.urls import path
from .views import keycloak_login, keycloak_callback, keycloak_logout

app_name = 'claveunica'

urlpatterns = [
    path('keycloak_login/', keycloak_login, name='keycloak_login'),
    path('callback/', keycloak_callback, name='keycloak_callback'),
    path('keycloak_logout/', keycloak_logout, name='keycloak_logout'),
]

applications/home/urls.py
from django.urls import path
from .views import generar_reporte_completo

from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
        ),

     path(
        'proceso-participativo',
        views.ProcesoParticipativoView.as_view(),
        name='proceso_participativo',
        ),

     path(
        'preguntas-frecuentes',
        views.PreguntasFrecuentesView.as_view(),
        name='preguntas_frecuentes',
        ),

    path(
        'documentos/',
        views.DocumentosView.as_view(),
        name='documentos',
        ),

    path(
        'politicas-privacidad',
        views.PoliticasPrivacidadView.as_view(),
        name='politicas_privacidad',
        ),

    path(
        'onboarding',
        views.OnboardingView.as_view(),
        name='onboarding',
    ),

    path(
        'descentralizacion_para_bienestar',
        views.DescentralizacionBienestarView.as_view(),
        name='descentralizacion-bienestar',
    ),
    path(
        'consejo_asesor',
        views.ConsejoAsesorListView.as_view(),
        name='consejo-asesor',
    ),
    path(
        'calendario_dialogos',
        views.CalendarioDialogosView.as_view(),
        name='calendario_dialogos',
    ),
     path(
         'generar_reporte_completo/', 
         generar_reporte_completo, 
         name='generar_reporte_completo'
    ),

]

applications/surveys/urls.py
from django.urls import path

from . import views

app_name = 'surveys_app'

urlpatterns = [

    path('comunas_por_region/<int:region_id>/', views.ComunasPorRegionView.as_view(), name='comunas_por_region'),
    path('consulta-datos-usuario/', views.ConsultaDatosUsuarioView.as_view(), name='consulta_datos_usuario'),
    path('pregunta-uno/', views.PreguntaUnoView.as_view(), name='pregunta_uno'),
    path('pregunta-dos/', views.PreguntaDosView.as_view(), name='pregunta_dos'),
    path('pregunta-tres/', views.PreguntaTresView.as_view(), name='pregunta_tres'),
    path('pregunta-cinco/', views.PreguntaCincoView.as_view(), name='pregunta_cinco'),
    path('pregunta-seis/', views.PreguntaSeisView.as_view(), name='pregunta_seis'),
    path('pregunta-siete/', views.PreguntaSieteView.as_view(), name='pregunta_siete'),
    path('enviar-formularios/', views.EnviarFormulariosViews.as_view(), name='enviar_formularios'),
    path('resumen-encuesta/', views.ResumenRespuestasUsuarioView.as_view(), name='resumen_encuesta')
    
]

hablemosdedescentralizacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.admin import admin_site 

#urls errores 
from django.conf.urls import handler404 , handler500 
from applications.home.views import Error404 , Error500 , Error503


urlpatterns = [
    path('admin/', admin_site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.surveys.urls')),
    re_path('', include('applications.claveunica.urls')),
    re_path('', include('applications.noticiasymedia.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404.as_view()

handler500 = Error500.as_error_view()

urlpatterns += [
path('503/', Error503.as_error_view(), name='error_503'),
]

applications/home/models.py
from django.db import models
from datetime import datetime

from django.core.validators import FileExtensionValidator
from .functions import validate_file_size_twenty
from ..regioncomuna.models import Region


class Countdown(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()

    def get_days_left(self):
        today = datetime.now().date()
        days_left = (self.end_date - today).days
        return days_left
    
    def get_days_until_start(self):
        today = datetime.now().date()
        days_until_start = (self.start_date - today).days
        return days_until_start

    def get_total_days(self):
        total_days = (self.end_date - self.start_date).days
        return total_days


class PreguntasFrecuentes(models.Model):

    pregunta_frecuente = models.CharField(max_length=400)
    respuesta_pregunta_frecuente = models.TextField()

    class Meta:
        verbose_name = 'Pregunta frecuente'
        verbose_name_plural = 'Pregunta frecuentes'

    def __str__(self):
        return self.pregunta_frecuente


class TipoDocumentos(models.Model):

    tipo_documento = models.CharField(max_length=50,  unique=True)

    class Meta:
        verbose_name = 'Tipo de documento'
        verbose_name_plural = 'Tipos de documento'

    def __str__(self):
        return self.tipo_documento


class SeccionDocumentos(models.Model):

    seccion_documento = models.CharField(max_length=100, unique=True)
    tipo_documento = models.ForeignKey(TipoDocumentos, blank=False, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'seccion de tipo de documento'
        verbose_name_plural = 'Secciones de tipo de documento'

    def __str__(self):
        return self.seccion_documento


class Documentos(models.Model):

    titulo_documento = models.CharField(max_length=200)
    public = models.BooleanField(default=True)
    seccion_documento = models.ForeignKey(SeccionDocumentos, blank=False, on_delete=models.CASCADE,
                                       related_name='seccion_documentos')
    documento = models.FileField(upload_to='documents',
                             validators=[
                                 FileExtensionValidator(
                                    ['pdf'], message='Solo se permiten archivos PDF.'), validate_file_size_twenty],
                                 null=True, blank=True)


    class Meta:
        verbose_name = 'Documento'
        verbose_name_plural = 'Documentos'

    def __str__(self):
        return self.titulo_documento


class ConsejoAsesor(models.Model):
    nombre_asesor = models.CharField(max_length=200)
    region = models.ForeignKey(Region, on_delete=models.CASCADE, related_name='regiones',  null=True, blank=True)
    curriculum = models.CharField(max_length=500, null=True, blank=True)
    avatar = models.ImageField(upload_to='avatars', null=True, blank=True)

    class Meta:
        verbose_name = 'Consejo Asesor'
        verbose_name_plural = 'Consejos Asesores'

    def __str__(self):
        return self.nombre_asesor

applications/home/views.py
from django.views.generic import TemplateView, ListView
from django.shortcuts import render
from applications.noticiasymedia.views import NoticiasView, MultimediaView, LatestAlbumsHome
# importar modelos
from .models import Countdown, PreguntasFrecuentes, Documentos, TipoDocumentos, SeccionDocumentos, ConsejoAsesor


from django.http import HttpResponse
from datetime import datetime
from django.contrib.auth.decorators import user_passes_test
from django.contrib.admin.views.decorators import staff_member_required
import csv
from applications.regioncomuna.models import Comuna
from applications.surveys.models import (
    PreguntaUno, PreguntaDos, PreguntaTres,
    PreguntaCinco, PreguntaSeis, PreguntaSiete
)
from applications.users.models import User


# importar apps de terceros


class HomePageView(NoticiasView, MultimediaView, LatestAlbumsHome):
    template_name = 'apps/home/home.html'
   

class ProcesoParticipativoView(TemplateView):
    template_name = 'apps/home/proceso_participativo.html'


class PreguntasFrecuentesView(TemplateView):
    template_name = 'apps/home/preguntas_frecuentes.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['preguntas'] = PreguntasFrecuentes.objects.all()
        return context


class DocumentosView(TemplateView):
    template_name = 'apps/home/documentos.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tipos_documentos = TipoDocumentos.objects.prefetch_related('secciondocumentos_set__seccion_documentos').all()
        context['tipos_documentos'] = tipos_documentos
        return context


class PoliticasPrivacidadView(TemplateView):
    template_name = 'apps/home/politicas_privacidad.html'

class CalendarioDialogosView(TemplateView):
    template_name = 'apps/home/calendario_dialogos.html'


class OnboardingView(TemplateView):
    template_name = 'apps/home/onboarding.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        countdown = Countdown.objects.first()
        if countdown is None:
            context['is_active'] = False
        else:
            days_until_start = countdown.get_days_until_start()
            days_left = countdown.get_days_left()
            context['is_active'] = (days_until_start <= 0) and (days_left >= 0)
        return context


class DescentralizacionBienestarView(TemplateView):
    template_name = 'apps/home/descentralizacion_bienestar.html'


class ConsejoAsesorListView(ListView):
    model = ConsejoAsesor
    template_name = 'apps/home/consejo_asesor_list.html'
    context_object_name = 'asesores'

    def get_queryset(self):
        # Ordenar por ID de manera descendente
        return ConsejoAsesor.objects.all().order_by('id')



class Error404(TemplateView):
    template_name = 'apps/errores/error404.html'

   
class Error500(TemplateView):
    template_name = 'apps/errores/error500.html'

    @classmethod
    def as_error_view(cls):

        v = cls.as_view()
        def view(request):
            r = v(request)
            r.render()
            return r
        return view


class Error503(TemplateView):
    template_name = 'apps/errores/error503.html'

    @classmethod
    def as_error_view(cls):
        v = cls.as_view()

        def view(request):
            r = v(request)
            r.render()
            return r

        return view
    
def superuser_required(view_func):
    decorated_view_func = user_passes_test(
        lambda u: u.is_superuser,
        login_url='/admin/login/'
    )(view_func)
    return decorated_view_func

@superuser_required
def generar_reporte_completo(request):
    # Obtener la fecha actual y formatearla
    fecha_actual = datetime.now().strftime('%Y-%m-%d')
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = f'attachment; filename="reporte_completo_{fecha_actual}.csv"'

    writer = csv.writer(response)
    writer.writerow([
        'region', 'comuna', 'genero', 'edad', 'pueblo_originario', 'fecha_encuesta_completada',
        PreguntaUno._meta.get_field('valor').verbose_name,
        PreguntaDos._meta.get_field('propuesta_1').verbose_name,
        PreguntaDos._meta.get_field('propuesta_2').verbose_name,
        PreguntaDos._meta.get_field('propuesta_3').verbose_name,
        PreguntaDos._meta.get_field('propuesta_4').verbose_name,
        PreguntaTres._meta.get_field('iniciativa_1').verbose_name,
        PreguntaTres._meta.get_field('iniciativa_2').verbose_name,
        PreguntaTres._meta.get_field('iniciativa_3').verbose_name,
        PreguntaTres._meta.get_field('iniciativa_4').verbose_name,
        PreguntaTres._meta.get_field('iniciativa_5').verbose_name,
        PreguntaCinco._meta.verbose_name,
        PreguntaSeis._meta.get_field('valor').verbose_name,
        PreguntaSiete._meta.get_field('texto_respuesta').verbose_name
    ])

    usuarios = User.objects.all()
    for usuario in usuarios:
        row = [
            usuario.comuna.region.region if usuario.comuna and usuario.comuna.region else '',
            usuario.comuna.comuna if usuario.comuna else '',
            usuario.get_genero_display(),
            usuario.edad,
            usuario.get_pueblo_originario_display(),
            usuario.fecha_encuesta_completada.strftime('%Y-%m-%d %H:%M:%S') if usuario.fecha_encuesta_completada else '',
        ]
        
        # PreguntaUno
        pregunta_uno = PreguntaUno.objects.filter(usuario=usuario).first()
        row.append(pregunta_uno.get_valor_display() if pregunta_uno else '')

        # PreguntaDos
        pregunta_dos = PreguntaDos.objects.filter(usuario=usuario).first()
        row.extend([
            pregunta_dos.get_propuesta_1_display() if pregunta_dos else '',
            pregunta_dos.get_propuesta_2_display() if pregunta_dos else '',
            pregunta_dos.get_propuesta_3_display() if pregunta_dos else '',
            pregunta_dos.get_propuesta_4_display() if pregunta_dos else ''
        ])
        
        # PreguntaTres
        pregunta_tres = PreguntaTres.objects.filter(usuario=usuario).first()
        row.extend([
            pregunta_tres.get_iniciativa_1_display() if pregunta_tres else '',
            pregunta_tres.get_iniciativa_2_display() if pregunta_tres else '',
            pregunta_tres.get_iniciativa_3_display() if pregunta_tres else '',
            pregunta_tres.get_iniciativa_4_display() if pregunta_tres else '',
            pregunta_tres.get_iniciativa_5_display() if pregunta_tres else ''
        ])
        
        # PreguntaCinco
        pregunta_cinco = PreguntaCinco.objects.filter(usuario=usuario).first()
        row.append(', '.join(pregunta_cinco.get_opciones_texto()) if pregunta_cinco else '')

        # PreguntaSeis
        pregunta_seis = PreguntaSeis.objects.filter(usuario=usuario).first()
        row.append(pregunta_seis.get_valor_display() if pregunta_seis else '')

        # PreguntaSiete
        pregunta_siete = PreguntaSiete.objects.filter(usuario=usuario).first()
        row.append(pregunta_siete.texto_respuesta if pregunta_siete else '')

        writer.writerow(row)

    return response

templates/apps/home/documentos.html
{% extends "base/base.html" %} 
{% load static %}
{% block views %}
{% load countdown_tags %}
{% load static extra_filters %}
<div>
    <div class="d-flex justify-content-center">
        <div class="col-md-8">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mt-5">
                    <li class="breadcrumb-item">
                        <a href="{%  url 'home_app:index' %}" class="text-primary">Inicio</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">Documentos</li>
                </ol>
            </nav>

            <div class="section-header mt-5">
                <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold" id="secciones">
                    Documentos
                </p>
            </div>
            <div class="section-body">
                <p class="h4 pb-4">
                    Si quieres tener más antecedentes para participar en la consulta, o para seguir este proceso, tenemos un repositorio de documentos de interés.
                </p>
            </div>
            <div class="my-3 col-md-6">{% countdown_component %}</div>
        </div>
    </div>

    <div>{% include "components/logo_banner.html"%}</div>

    <div class="d-flex justify-content-center">
        <div class="col-md-8 mb-5">

            <div id="documentos-documentosnormativos" class="my-5 pt-md-2">
                <div id="dnContainer">
                 {% for tipo_documento in tipos_documentos %}
                    {% if tipo_documento|has_documents:True %}
                        <p class="font-level-2 pb-2 text-md-left text-black font-weight-bold m-4" id="{{ tipo_documento }}">
                        {{ tipo_documento }}
                        </p>

                        {% for seccion_documento in tipo_documento.secciondocumentos_set.all %}
                            {% if seccion_documento|has_public_documents %}
                                <div class="card-data-list card-data-list-flush m-4 bg-gray-200" id="{{ seccion_documento }}">
                                    <ol class="list-unstyled w-100"  id="collapsibleFlushAccordion{{ forloop.parentloop.counter }}_{{ forloop.counter }}" >
                                        <li>
                                            <button class="btn text-left w-100 d-flex align-items-start justify-content-between py-4 px-3"
                                            id="collapsibleFlushHeading{{ forloop.parentloop.counter }}_{{ forloop.counter }}"
                                            type="button"
                                            data-toggle="collapse"
                                            data-target="#collapsibleFlushCollapse{{ forloop.parentloop.counter }}_{{ forloop.counter }}"
                                            aria-controls="collapsibleFlushCollapse{{ forloop.parentloop.counter }}_{{ forloop.counter }}"
                                            aria-expanded="false">
                                                <span class="font-level-3 mb-0">{{ seccion_documento }}</span>
                                                <span class="toggler-icon cl cl-m-arrow-down cl-2x" aria-hidden="true"></span>
                                            </button>
                                            <div class="collapse"
                                            id="collapsibleFlushCollapse{{ forloop.parentloop.counter }}_{{ forloop.counter }}"
                                            aria-labelledby="collapsibleFlushHeading{{ forloop.parentloop.counter }}_{{ forloop.counter }}"
                                            data-parent="#collapsibleFlushAccordion{{ forloop.parentloop.counter }}_{{ forloop.counter }}">
                                                <div class="pr-5 pb-3 pl-3 pt-3 border-top border-gray-b">
                                                    <ul class="list-group">
                                                        {% for documento in seccion_documento|public_documents %}
                                                            <li class="list-group-item bg-transparent border-0 d-flex justify-content-between align-items-center">
                                                                {{ documento }}
                                                                <a type="button" class="btn btn-neutral btn-lg btn-default-size text-white border-white bg-primary mb-4" type="button" href="{{ documento.documento.url }}" target="_blank">
                                                                    Descargar
                                                                    <i class="material-symbols-outlined">
                                                                        download
                                                                    </i>
                                                                </a>
                                                            </li>
                                                        {% endfor %}
                                                    </ul>
                                                </div>
                                            </div>
                                        </li>
                                    </ol>
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                {% endfor %}
                </div>
            </div>

            <div>{% include "components/invitacion.html"%}</div>
        </div>
    </div>
</div>
{% endblock views %}

{% block scripts %}

{% endblock %}

templates/apps/home/onboarding.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}

<section class="container-hero">
    
    <div class="container">
        <section class="col-md-12">
            <div class="section-header mt-5 d-flex flex-column align-items-center">
                <div class="col-12 col-md-6">
                    {% include "components/desentralizacion_banner.html" %}
                </div>
                <p class="col-md-8 font-level-1 pb-md-4 text-center font-weight-bold" id="secciones">Te damos la bienvenida a la consulta ciudadana</p>
                <p class="h4 mb-5">
                    Te damos la bienvenida a esta consulta ciudadana, donde puedes acceder vía Clave Única, y a
                    través de seis preguntas ser parte, desde tu experiencia y percepción, de la construcción de la
                    Política de Descentralización de Chile, con la que buscamos contribuir al desarrollo social y
                    económico de las diversas comunidades del país.<br/><br/>
                    La descentralización es un proceso de redistribución de responsabilidades, recursos y capacidades,
                    desde ministerios y servicios públicos, hacia municipalidades y gobiernos regionales, para un
                    mayor bienestar de las personas y sus comunidades.<br/><br/>
                    Nota: Esta consulta es de carácter público, y tanto la información personal como las respuestas
                    serán tratadas de manera confidencial. Si bien los resultados de este cuestionario no son
                    vinculantes, contribuirán en gran medida a establecer el horizonte que busca la elaboración de la
                    Política de Descentralización de Chile.<br/><br/>
                    Tiempo estimado de respuesta: cinco minutos.
                </p>
            </div>

            <div class="my-3 d-flex flex-column align-items-center">
                <div class="mx-auto" >
                    {% if user.is_authenticated %}
                        {% if user.encuesta_completada %}
                            <p class="h4 text-center">Ya has contestado esta encuesta.</p>
                            <div class="col d-flex justify-content-center">
                                <button class="btn btn-neutral btn-default-size text-white border-white bg-primary mb-4"
                                        type="button"
                                        onclick="window.location.href='{% url 'surveys_app:enviar_formularios' %}'">
                                    Ir a Recibir mis respuestas
                                    <i class="material-symbols-outlined">
                                    chevron_right
                                    </i>
                                </button>
                            </div>
                        {% else %}
                            <div class="col d-flex justify-content-center">
                                <button class="btn btn-neutral btn-default-size text-white border-white bg-primary mb-4"
                                        type="button"
                                        onclick="window.location.href='{% url 'surveys_app:consulta_datos_usuario' %}'"
                                        {% if not is_active %}disabled{% endif %}>
                                    Comenzar el Proceso
                                    <i class="material-symbols-outlined">
                                    chevron_right
                                    </i>
                                </button>
                            </div>
                        {% endif %}
                    {% else %}
                        <div class="col d-flex justify-content-center">
                            <button class="btn btn-neutral btn-default-size text-white border-white bg-primary mb-4"
                                    type="button" onclick="window.location.href='{% url 'claveunica:keycloak_login' %}'">
                                Inicia sesión con Clave Única
                                <i class="material-symbols-outlined">
                                chevron_right
                                </i>
                            </button>
                        </div>
                    {% endif %}

                </div>
                <div class="col-md-5 text-center mb-5">
                    {% countdown_component %}
                </div>
            </div>    
        </section>
    </div> 

    <div class="mt-md-5">
        {% include "components/logo_banner.html" %}
    </div> 

</section> 
  
{% endblock views %}

templates/apps/home/preguntas_frecuentes.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}

<div>
    <div  class="d-flex justify-content-center">
        <div class="col-md-8">
            
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mt-5">
                  <li class="breadcrumb-item text-primary"><a href="/" class="text-primary">Inicio</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Preguntas Frecuentes</li>
                </ol>
            </nav>

            <div class="section-header mt-5">
            <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold" id="secciones">Preguntas Frecuentes</p>
            </div>
            <div class="section-body">
            <p class="h4 pb-4">Resolvemos tus dudas sobre el proceso participativo para la elaboración de la Política Nacional de Descentralización: mecanismos, plazos, etapas y más.</p>
            </div>
            <div class="my-3 col-md-6">
                {% countdown_component %}
            </div>
        </div>
    </div>
    
    <div>
        {% include "components/logo_banner.html"%}
    </div>

    <div  class="d-flex justify-content-center">
        <div class="col-md-8">
            <div id="colapsables_container">
                <div>
                    {% for pregunta in preguntas %}
                        {% include "components/colapsable.html" with titulo=pregunta.pregunta_frecuente contenido=pregunta.respuesta_pregunta_frecuente %}
                    {% endfor %}
                </div>
            </div>
            <div>
                {% include "components/invitacion.html"%}
            </div>
        </div>     
    </div>

</div>
{% endblock views %}

templates/apps/home/proceso_participativo.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}

<section class="container-fluid mt-5">

    <div  class="d-flex justify-content-center">
        <div class="col-md-8">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mt-5">
                  <li class="breadcrumb-item text-primary"><a href="/" class="text-primary">Inicio</a></li>
                  <li class="breadcrumb-item active" aria-current="page">Proceso Participativo</li>
                </ol>
            </nav>

            <div class="section-header mt-5">
            <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold" id="secciones">Proceso Participativo</p>
            </div>
            <div class="section-body">
            <p class="h4 pb-4">El proceso participativo para la elaboración de la Política de Descentralización de Chile considera cuatro instancias. 
                Conoce en qué consiste cada una y a quiénes van dirigidas.</p>
            </div>
            <div class="my-5 col-md-6">
                {% countdown_component %}
            </div>
        </div>
    </div>
    
    <div class="my-4">
        {% include "components/logo_banner.html"%}
    </div>

    <div class="container my-md-5">
<!-- aqui estan las columnas -->
        <div class="d-flex justify-content-center">
            <div class="col-md-10">
                {% include "components/invitacion.html"%}
            </div>
        </div>
        <div class="d-flex justify-content-center mt-4">
            <div class="parent col-lg-10 align-items-start">
                
                <div class="div1 section-header">
                    <p class="font-level-2 text-center pb-4 text-black font-weight-bold">Diálogos regionales para la Política de Descentralización de Chile</p>
                    <p class="h4 text-left mb-md-0 text-body mt-4">Se realizarán diálogos participativos en cada una de las 16 regiones del país, convocando a autoridades 
                        nacionales, regionales y locales, mundo académico, sector público, sociedad civil, y representantes de cada región.</p>
                </div>
                <div class="div2 d-flex flex-column align-items-center w-100 mt-4">
                    <button class="btn btn-neutral btn-lg text-nowrap text-primary border-primary bg-white" type="button" onclick="window.location.href='{% url 'home_app:documentos' %}#Documentos Normativos'">
                        Ver documentos relacionados
                        <i class="material-symbols-outlined ml-1">
                            chevron_right
                        </i>
                    </button>
                </div>
                <div class="div3 section-header mt-5 mt-lg-0">
                    <p class="font-level-2 text-center pb-4 text-black font-weight-bold">Seminarios Virtuales</p>
                    <p class="h4 text-left mb-md-0 text-body mt-4">Se realizarán encuentros telemáticos, convocando a audiencias específicas, tales como centros de estudios, 
                        asociaciones gremiales de funcionarios y funcionarias de gobiernos regionales y municipios, funcionarios y funcionarias del nivel central, organizaciones 
                        no gubernamentales, organismos internacionales, y organizaciones de pueblos indígenas.</p>
                </div>
                <div class="div4 d-flex flex-column align-items-center w-100 mt-4">
                    <button class="btn btn-neutral btn-lg text-nowrap text-primary border-primary bg-white" type="button" onclick="window.location.href='{% url 'home_app:documentos' %}#Seminarios Virtuales'">
                        Ver documentos relacionados
                        <i class="material-symbols-outlined ml-1">
                            chevron_right
                        </i>
                    </button>
                </div>
                <div class="div5 section-header mt-5 mt-lg-0">
                    <p class="font-level-2 text-center pb-4 text-black font-weight-bold">Encuentros Macrozonales de Asociaciones de Municipalidades</p>
                    <p class="h4 text-left mb-md-0 text-body mt-4">En el marco del Tercer Encuentro de Asociaciones de Municipios, se desarrollarán tres encuentros en las 
                        macrozonas norte, centro y sur del país, que contribuyan a la Política de Descentralización de Chile. Botón “Revisa aquí el calendario de los 
                        Encuentros Macrozonales de Asociaciones de Municipalidades” y redirecciona.</p>
                </div>
                <div class="div6 d-flex flex-column align-items-center w-100 mt-4">
                    <button class="btn btn-neutral btn-lg text-nowrap text-primary border-primary bg-white" type="button" onclick="window.location.href='{% url 'home_app:documentos' %}#Participación de los Consejos de la Sociedad Civil (COSOC)'">
                        Ver documentos relacionados
                        <i class="material-symbols-outlined ml-1">
                            chevron_right
                            </i>
                    </button>
                </div>  
            </div>
        </div>
    </div>
</div>
</section>
{% endblock views %}