applications/home/urls.py
from django.urls import path
from .views import generar_reporte_completo

from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
        ),

     path(
        'proceso-participativo',
        views.ProcesoParticipativoView.as_view(),
        name='proceso_participativo',
        ),

     path(
        'preguntas-frecuentes',
        views.PreguntasFrecuentesView.as_view(),
        name='preguntas_frecuentes',
        ),

    path(
        'documentos/',
        views.DocumentosView.as_view(),
        name='documentos',
        ),

    path(
        'politicas-privacidad',
        views.PoliticasPrivacidadView.as_view(),
        name='politicas_privacidad',
        ),

    path(
        'onboarding',
        views.OnboardingView.as_view(),
        name='onboarding',
    ),

    path(
        'descentralizacion_para_bienestar',
        views.DescentralizacionBienestarView.as_view(),
        name='descentralizacion-bienestar',
    ),
    path(
        'consejo_asesor',
        views.ConsejoAsesorListView.as_view(),
        name='consejo-asesor',
    ),
    path(
        'calendario_dialogos',
        views.CalendarioDialogosView.as_view(),
        name='calendario_dialogos',
    ),
     path(
         'generar_reporte_completo/', 
         generar_reporte_completo, 
         name='generar_reporte_completo'
    ),

]

applications/noticiasymedia/urls.py
from django.urls import path

from . import views
from .views import  NoticiaDetailView, LatestAlbumsByRegionView, AlbumsByRegionView, FileFieldFormView

app_name = 'noticiasymedia_app'

urlpatterns = [
    path('noticias/', views.NoticiasView.as_view(), name='noticias'),
    path('multimedia/', views.MultimediaView.as_view(), name='multimedia'),
    path('noticias/<slug>/', NoticiaDetailView.as_view(), name='noticia_detail'),
    path('multimedia/<slug>/', views.MultimediaDetailView.as_view(), name='multimedia_detail'),
    path('fotos/', LatestAlbumsByRegionView.as_view(), name='albums'),
    path('fotos/<int:region_id>/', AlbumsByRegionView.as_view(), name='albums_by_region'),
    path('upload_photos/', FileFieldFormView.as_view(), name='upload_photos'),
]

hablemosdedescentralizacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.admin import admin_site 

#urls errores 
from django.conf.urls import handler404 , handler500 
from applications.home.views import Error404 , Error500 , Error503


urlpatterns = [
    path('admin/', admin_site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.surveys.urls')),
    re_path('', include('applications.claveunica.urls')),
    re_path('', include('applications.noticiasymedia.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404.as_view()

handler500 = Error500.as_error_view()

urlpatterns += [
path('503/', Error503.as_error_view(), name='error_503'),
]

applications/noticiasymedia/models.py
# standard library
from datetime import timedelta, datetime

from django.core.exceptions import ValidationError
#
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.safestring import mark_safe
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill, ResizeToFit, Transpose
# apps de terceros
from model_utils.models import TimeStampedModel

from applications.regioncomuna.models import Region


class Tag(models.Model):
    tag = models.CharField(
        max_length=20, verbose_name='Tag', unique=True)

    def __str__(self):
        return self.tag


class Noticias(TimeStampedModel):
    titulo_noticia = models.CharField(max_length=150 ,verbose_name='Titulo Noticia (obligatorio)', unique=True)
    bajada_noticia = models.CharField(max_length=150, verbose_name='Bajada noticia(obligatorio)')
    contenido_noticia = models.TextField(verbose_name='contenido Noticia (obligatorio)')
    autor = models.CharField(max_length=100, verbose_name='autor (opcional)', blank=True)
    slug = models.SlugField(editable=False, max_length=300)
    tag = models.ManyToManyField(
        Tag, blank=False, verbose_name='Tag noticia')
    portada_noticia= ProcessedImageField(
        upload_to='noticias', processors=[Transpose(), ResizeToFit(1200, 630)],
        format='WEBP',
        options={'quality': 60},
        null=True,
        blank=False,
        verbose_name='Foto Portada (obligatorio)'
    )
    galeria_url = models.URLField(max_length=200, null=True,
                            blank=True, verbose_name='Url galeria de fotos')
    public = models.BooleanField(default=True, verbose_name='publico')

    def __str__(self):
        return self.titulo_noticia

    def save(self, *args, **kwargs):
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.titulo_noticia, str(seconds))

        self.slug = slugify(slug_unique)

        super(Noticias, self).save(*args, **kwargs)
    
    
class Multimedia(TimeStampedModel):
    titulo_multimedia = models.CharField(max_length=200,verbose_name='Titulo Multimedia (obligatorio)', unique=True)
    descripcion_multimedia = models.TextField(verbose_name='Descripcion')
    autor = models.CharField(max_length=100, verbose_name='autor (opcional)', blank=True)
    video_url = models.URLField(max_length=200, null=True,
                            verbose_name='Url video Youtube (obligatorio)')
    tag = models.ManyToManyField(
            Tag, blank=False, verbose_name='Tag Multimedia')
    slug = models.SlugField(editable=False, max_length=300, default='video') 
    public = models.BooleanField(default=True, verbose_name='publico')

    def __str__(self):
        return self.titulo_multimedia
    def save(self, *args, **kwargs):
        now = datetime.now()
        total_time = timedelta(
            hours=now.hour,
            minutes=now.minute,
            seconds=now.second
        )    
        seconds = int(total_time.total_seconds())
        slug_unique = '%s %s' % (self.titulo_multimedia, str(seconds))
        
        self.slug = slugify(slug_unique)
        
        super(Multimedia, self).save(*args,**kwargs)


class PhotoAlbum(TimeStampedModel):
    titulo_album = models.CharField(max_length=200, verbose_name='Titulo Album', null=True, blank=True)
    descripcion_album = models.CharField(max_length=500, verbose_name='Descripcion Album (obligatorio)')
    region = models.ForeignKey(Region, on_delete=models.CASCADE, verbose_name='Region (obligatorio)')
    date = models.DateField(verbose_name='Fecha del Álbum (obligatorio)')
    foto_portada = ProcessedImageField(upload_to='album_photos', processors=[
        ResizeToFill(1200, 630)], format='WEBP', options={'quality': 60}, null=True,
        blank=False, verbose_name='Foto Portada (obligatorio)')
    autor = models.ForeignKey(
        'users.User', on_delete=models.CASCADE, verbose_name='Autor')
    public = models.BooleanField(default=True, verbose_name='Público')

    def __str__(self):
        return self.titulo_album if self.titulo_album else "Álbum sin título"

    class Meta:
        ordering = ['region__region']
        unique_together = ('region', 'date')


class Photo(TimeStampedModel):
    album = models.ForeignKey(
        PhotoAlbum, on_delete=models.CASCADE, verbose_name='Album')
    foto = ProcessedImageField(
        upload_to='album',
        processors=[Transpose(), ResizeToFit(1200, 630)],
        format='WEBP',
        options={'quality': 60},
        null=True,
        blank=False,
        verbose_name='Foto (obligatorio)'
    )
    descripcion = models.CharField(
        max_length=500, verbose_name='Descripcion Foto (opcional)', 
        null=True,
        blank=True
    )

    def __str__(self):
        return self.descripcion or ""

    def save(self, *args, **kwargs):
        self.clean()  # Llama a clean para realizar la validación antes de guardar
        super().save(*args, **kwargs)

    def preview(self):
        if self.foto:
            return mark_safe(f'<img src="{self.foto.url}" width="150" height="150" />')
        return "No Image"

    preview.short_description = 'Preview'

applications/noticiasymedia/forms.py
# forms.py
from django import forms

class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True

class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result

class FileFieldForm(forms.Form):
    file_field = MultipleFileField()

applications/noticiasymedia/views.py
from typing import Any, Dict
import datetime
from django.shortcuts import render, redirect
from applications.noticiasymedia.models import Noticias, Multimedia, PhotoAlbum, Photo
from django.views.generic import TemplateView, DetailView, ListView
from django.core.paginator import Paginator
from django.db.models import Max

from applications.regioncomuna.models import Region
from django.db import models
from .forms import FileFieldForm
from django.views.generic.edit import FormView
from applications.regioncomuna.models import Region
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import user_passes_test


class NoticiasView(TemplateView):
    template_name = 'apps/noticiasymedia/noticias.html'
    paginate_by = 6
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        noticias = Noticias.objects.all()
        paginator = Paginator(noticias, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['noticias'] = page_obj
        
        return context    


class NoticiaDetailView(DetailView):
    template_name = 'apps/noticiasymedia/noticia_detail.html'
    model = Noticias
    context_object_name = 'noticia'

    
class MultimediaView(TemplateView):
    template_name = 'apps/noticiasymedia/multimedia.html'
    paginate_by = 6 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        multimedias = Multimedia.objects.all()
        paginator = Paginator(multimedias, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['multimedias'] = page_obj
        
        return context


class MultimediaDetailView(DetailView):
    template_name = 'apps/noticiasymedia/media_detail.html'
    model = Multimedia
    context_object_name = 'multimedia'


class LatestAlbumsByRegionView(TemplateView):
    template_name = 'apps/noticiasymedia/album.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        regions_with_latest_album_date = Region.objects.annotate(
            latest_album_date=Max('photoalbum__date')
        ).order_by('id')  # Ordena las regiones por nombre

        latest_albums = []
        for region in regions_with_latest_album_date:
            latest_album = PhotoAlbum.objects.filter(
                region=region,
                date=region.latest_album_date,
                public=True
            ).order_by('-date').first()  # Asegúrate de que también aquí se ordena por fecha si es necesario
            if latest_album:
                latest_albums.append(latest_album)

        context['albums'] = latest_albums
        return context


class LatestAlbumsHome(TemplateView):
    paginate_by = 3  # Define cuántos elementos por página quieres mostrar

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Ordenar todos los álbumes por fecha de última modificación
        all_albums = PhotoAlbum.objects.filter(
            public=True  # Añadir filtro para mostrar solo álbumes públicos
        ).order_by('-modified')

        # Aplicar la paginación
        paginator = Paginator(all_albums, self.paginate_by)
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['latest_albums'] = page_obj
        return context


class AlbumsByRegionView(ListView):
    model = PhotoAlbum
    template_name = 'apps/noticiasymedia/albums_by_region.html'
    context_object_name = 'albums'

    def get_queryset(self):
        region_id = self.kwargs['region_id']
        return PhotoAlbum.objects.filter(
            region_id=region_id,
            public=True  # Añadir filtro para mostrar solo álbumes públicos
        ).order_by('-date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        region = Region.objects.get(pk=self.kwargs['region_id'])
        context['region_name'] = region.region
        return context
    

@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class FileFieldFormView(FormView):
    form_class = FileFieldForm
    template_name = "components/upload_photos.html"
    success_url = "/upload_photos/"  # Redirige al índice del admin después de la subida

    def form_valid(self, form):
        try:
            last_album = PhotoAlbum.objects.latest('id')  # Obtener el último álbum creado
        except PhotoAlbum.DoesNotExist:
            return self.form_invalid(form)  # Si no hay álbumes, manejar el error adecuadamente

        files = form.cleaned_data["file_field"]
        for f in files:
            Photo.objects.create(album=last_album, foto=f)
        return super().form_valid(form)

templates/apps/noticiasymedia/album.html
{% extends "base/base.html" %}
{% load static %}
{% load countdown_tags %}

{% block views %}
<section class="container-fluid my-5 px-0">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-md-10 col-lg-10 col-xl-8">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mt-0 mx-5">
          <li class="breadcrumb-item">
            <a href="{% url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Fotos</li>
        </ol>
      </nav>
      <div class="section-header mt-5">
        <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold">Fotos</p>
      </div>
      <div class="container p-0 section-body mb-4">
        {% countdown_component %}
      </div>
    </div>
  </div>
  <div class="px-0">
    {% include "components/logo_banner.html" %}
  </div>
  {% if albums %}
    <div class="cols-cards-12">
      <div class="container row mx-md-1 mx-auto">
        {% include "components/card_foto.html" %}
      </div>
    </div>
  {% else %}
    <div class="container my-2">
      <p class="font-level-3 text-center font-weight-bold">Aún no hay fotos publicadas</p>
    </div>
  {% endif %}
</section>
{% endblock %}

templates/apps/noticiasymedia/albums_by_region.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}

<section class="container my-5 px-0">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-md-10">
      <nav aria-label="breadcrumb ">
        <ol class="breadcrumb mt-0 mx-5">
          <li class="breadcrumb-item">
            <a href="{%  url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Fotos</li>
        </ol>
      </nav>

      <div class="section-header mt-5">
        <p>Última actualización: </p>
        <p class="font-level-1 pb-1 text-md-left text-center text-black font-weight-bold">Diálogo Regional {{ region_name }}</p>
      </div>
      <div class="section-body my-4">
        {% countdown_component %}</div>
    </div>
  </div>
  <div class="px-0">
    {% include "components/logo_banner.html" %}
  </div>

  <!-- albums -->
  <div class="container col-md-10 my-md-5">
    {% for album in albums %}
        <div class="container my-md-5">
            {% if album.titulo_album %}
                <p class="font-level-1 pb-1 text-md-left text-start text-black font-weight-bold">{{ album.titulo_album }}</p>
            {% else %}
                <p class="font-level-1 pb-1 text-md-left text-start text-black font-weight-bold">Diálogo regional {{ region_name }} realizado el {{ album.date }}</p>
            {% endif %}
            <p>{{ album.descripcion_album }}</p>
            <div class="d-flex flex-wrap">
                {% for photo in album.photo_set.all %}
                    <img src="{{ photo.foto.url }}" alt="{{ photo.descripcion }}" class="imagen-card" data-toggle="modal" data-target="#photo-modal-{{ photo.id }}">
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>

<!-- modal -->
{% for album in albums %}
    {% for photo in album.photo_set.all %}
    <div class="modal fade custom-photo-modal" id="photo-modal-{{ photo.id }}" tabindex="-1" role="dialog" aria-labelledby="photo-modal-label-{{ photo.id }}" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered custom-modal-dialog" role="document">
        <div class="modal-content custom-modal-content">
          <div class="modal-header">
            {% if photo.descripcion %}
              <h5 class="modal-title" id="photo-modal-label-{{ photo.id }}">{{ photo.descripcion }}</h5>
            {% else %}
              <h5 class="modal-title" id="photo-modal-label-{{ photo.id }}"></h5>
            {% endif %}
            <button type="button" class="close" data-dismiss="modal" aria-label="Cerrar">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <img src="{{ photo.foto.url }}" alt="{{ photo.descripcion }}" class="img-fluid custom-modal-image">
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  {% endfor %}

</section>
{% endblock %}

templates/apps/noticiasymedia/media_detail.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}

<section class="container-fluid mt-5">
  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mt-1">
          <li class="breadcrumb-item">
            <a href="{% url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page"><a
              href="{% url 'noticiasymedia_app:multimedia'%}">Videos</a></li>
        </ol>
      </nav>
      <div>
        <div class="head-news my-5 ">
          <div class="title-news">
            <p class="font-level-7"><strong>Fecha de publicación: </strong>{{ multimedia.created|date:"l j \\d\\e F \\d\\e Y" }}</p>
            <p class="font-level-1 text-center text-md-left ">{{ multimedia.titulo_multimedia }}</p>
          </div>
          <div class="embed-responsive embed-responsive-16by9">
            <iframe  src="{{ multimedia.video_url }}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
          </div>
          <div>
            <p class="text-body-news my-2">{{ multimedia.descripcion_multimedia }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/apps/noticiasymedia/multimedia.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}
<section class="container-fluid my-5 px-0">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-md-10 col-lg-10 col-xl-8">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mt-0">
          <li class="breadcrumb-item">
            <a href="{%  url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Videos</li>
        </ol>
      </nav>

      <div class="section-header mt-5 px-0">
        <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold">
          Videos
        </p>
      </div>
      <div class="section-body my-4">
        {% countdown_component %}</div>
    </div>
  </div>
  <div class="container-fluid">
    {% include "components/logo_banner.html" %}
  </div>

  <!--card videos -->
  {% if multimedias %}
  <div class="cols-cards-12">
    <div class="row mx-md-1 mx-auto">
      {% include "components/card_media.html"%}
    </div>
  </div>
  {% else %}
  <!-- Mostrar el mensaje si no hay contenido multimedia registrado -->
  <div class="container my-2">
    <p class="font-level-3 text-center font-weight-bolder ">Aún no hay videos publicados</p>
  </div>
{% endif %}
    <!-- Paginación -->
<nav class="pagination-container flex-column flex-sm-row justify-content-center a11y-fonts-flex-column a11y-fonts-flex-lg-row">
  <p class="text-center">{{ multimedias.start_index }} - {{ multimedias.end_index }} de {{ multimedias.paginator.count }} videos </p>
  <ul class="pagination justify-content-center align-items-center active">
      {% if multimedias.has_previous %}
      <li class="page-item">
          <a class="page-link border-0 text-decoration-none font-level-1" href="?page={{ multimedias.previous_page_number }}">
              &lt;
          </a>
      </li>
      {% endif %}
      {% for num in multimedias.paginator.page_range %}
      {% if num == multimedias.number %}
      <li class="page-item active">
          <a class="page-link border-0 text-decoration-none" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% else %}
      <li class="page-item">
          <a class="page-link border-0 text-decoration-none" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% endif %}
      {% endfor %}
      {% if multimedias.has_next %}
      <li class="page-item">
          <a class="page-link border-0 font-level-1 text-decoration-none" href="?page={{ multimedias.next_page_number }}">
              &gt;
          </a>
      </li>
      {% endif %}
  </ul>
</nav>
  </div>
</section>
{% endblock %}

templates/apps/noticiasymedia/noticia_detail.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}

<section class="container-fluid mt-5">
  <div class="d-flex justify-content-center">
    <div class="col-md-8">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb mt-1">
          <li class="breadcrumb-item">
            <a href="{% url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'noticiasymedia_app:noticias'%}">Noticias</a></li>
        </ol>
      </nav>
      <div>
        <div class="head-news my-5 ">
          <div class="title-news">
            <p class="font-level-7"><strong>Fecha de publicación: </strong>{{ noticia.created|date:"l j \\d\\e F \\d\\e Y" }}</p>
            <p class="font-level-1 text-center text-md-left ">{{ noticia.titulo_noticia }}</p>
          </div>
          <div>
            <img src="{{ noticia.portada_noticia.url }}" class="img-fluid mx-xl-auto" alt="Portada noticia">
          </div>
        </div>
        <div class="mb-5">
          <p class="font-level-5">{{ noticia.bajada_noticia }}</p>
          <p class=" text-body-news">{{ noticia.contenido_noticia|linebreaksbr }}</p>

          {% if noticia.galeria_url %}
        <div class="my-4">
          <p class="font-level-3 text-center font-weight-bold">Galeria de Imagenes</p>
          <p class="text-body-news">Puedes ver las fotos relacionadas a esta noticia en nuestro Flickr.</p>
          <div class="d-flex justify-content-center">
            <a class="btn btn-primary btn-lg btn-block my-3 w-50 " href="{{ noticia.galeria_url }}" type="button">Ver galería de imágenes</a>
          </div>
          {% endif %}
        </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/apps/noticiasymedia/noticias.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
{% load countdown_tags %}
<section class="container-fluid my-5 px-0">
  <div class="d-flex justify-content-center">
    <div class="col-12 col-md-10 col-lg-10 col-xl-8">
      <nav aria-label="breadcrumb ">
        <ol class="breadcrumb mt-0 mx-5">
          <li class="breadcrumb-item">
            <a href="{%  url 'home_app:index' %}" class="text-primary">Inicio</a>
          </li>
          <li class="breadcrumb-item active" aria-current="page">Noticias</li>
        </ol>
      </nav>

      <div class="section-header mt-5">
        <p class="font-level-1 pb-4 text-md-left text-center text-black font-weight-bold">
          Noticias
        </p>
      </div>
      <div class="section-body my-4">
        {% countdown_component %}</div>
    </div>
  </div>
  <div class="px-0">
    {% include "components/logo_banner.html" %}
  </div>

  <!--card news -->
  {% if noticias %}
    <div class="cols-cards-12" >
    <div class="row mx-md-1 mx-auto" >
          {% include "components/card_noticia.html"%}
      </div>
    </div>
  {% else %}
  <!-- Mostrar el mensaje si no hay noticias registradas -->
  <div class="container my-2">
    <p class="font-level-3 text-center font-weight-bold">Aún no hay noticias publicadas</p>
  </div>
  {% endif %}
  
    <!-- Paginación -->
<nav class="pagination-container flex-column flex-sm-row justify-content-center a11y-fonts-flex-column a11y-fonts-flex-lg-row">
  <p class="text-center">{{ noticias.start_index }} - {{ noticias.end_index }} de {{ noticias.paginator.count }} noticias </p>
  <ul class="pagination justify-content-center align-items-center active">
      {% if noticias.has_previous %}
      <li class="page-item">
          <a class="page-link border-0 text-decoration-none font-level-1" href="?page={{ noticias.previous_page_number }}">
              &lt;
          </a>
      </li>
      {% endif %}
      {% for num in noticias.paginator.page_range %}
      {% if num == noticias.number %}
      <li class="page-item active">
          <a class="page-link border-0 text-decoration-none" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% else %}
      <li class="page-item">
          <a class="page-link border-0 text-decoration-none" href="?page={{ num }}">{{ num }}</a>
      </li>
      {% endif %}
      {% endfor %}
      {% if noticias.has_next %}
      <li class="page-item">
          <a class="page-link border-0 font-level-1 text-decoration-none" href="?page={{ noticias.next_page_number }}">
              &gt;
          </a>
      </li>
      {% endif %}
  </ul>
</nav>
  </div>
</section>
{% endblock %}