applications/home/urls.py
from django.urls import path
from .views import generar_reporte_completo

from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
        ),

     path(
        'proceso-participativo',
        views.ProcesoParticipativoView.as_view(),
        name='proceso_participativo',
        ),

     path(
        'preguntas-frecuentes',
        views.PreguntasFrecuentesView.as_view(),
        name='preguntas_frecuentes',
        ),

    path(
        'documentos/',
        views.DocumentosView.as_view(),
        name='documentos',
        ),

    path(
        'politicas-privacidad',
        views.PoliticasPrivacidadView.as_view(),
        name='politicas_privacidad',
        ),

    path(
        'onboarding',
        views.OnboardingView.as_view(),
        name='onboarding',
    ),

    path(
        'descentralizacion_para_bienestar',
        views.DescentralizacionBienestarView.as_view(),
        name='descentralizacion-bienestar',
    ),
    path(
        'consejo_asesor',
        views.ConsejoAsesorListView.as_view(),
        name='consejo-asesor',
    ),
    path(
        'calendario_dialogos',
        views.CalendarioDialogosView.as_view(),
        name='calendario_dialogos',
    ),
     path(
         'generar_reporte_completo/', 
         generar_reporte_completo, 
         name='generar_reporte_completo'
    ),

]

applications/surveys/urls.py
from django.urls import path

from . import views

app_name = 'surveys_app'

urlpatterns = [

    path('comunas_por_region/<int:region_id>/', views.ComunasPorRegionView.as_view(), name='comunas_por_region'),
    path('consulta-datos-usuario/', views.ConsultaDatosUsuarioView.as_view(), name='consulta_datos_usuario'),
    path('pregunta-uno/', views.PreguntaUnoView.as_view(), name='pregunta_uno'),
    path('pregunta-dos/', views.PreguntaDosView.as_view(), name='pregunta_dos'),
    path('pregunta-tres/', views.PreguntaTresView.as_view(), name='pregunta_tres'),
    path('pregunta-cinco/', views.PreguntaCincoView.as_view(), name='pregunta_cinco'),
    path('pregunta-seis/', views.PreguntaSeisView.as_view(), name='pregunta_seis'),
    path('pregunta-siete/', views.PreguntaSieteView.as_view(), name='pregunta_siete'),
    path('enviar-formularios/', views.EnviarFormulariosViews.as_view(), name='enviar_formularios'),
    path('resumen-encuesta/', views.ResumenRespuestasUsuarioView.as_view(), name='resumen_encuesta')
    
]

hablemosdedescentralizacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.admin import admin_site 

#urls errores 
from django.conf.urls import handler404 , handler500 
from applications.home.views import Error404 , Error500 , Error503


urlpatterns = [
    path('admin/', admin_site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.surveys.urls')),
    re_path('', include('applications.claveunica.urls')),
    re_path('', include('applications.noticiasymedia.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404.as_view()

handler500 = Error500.as_error_view()

urlpatterns += [
path('503/', Error503.as_error_view(), name='error_503'),
]

applications/surveys/models.py
from django.db import models
from django.core.exceptions import ValidationError


class PreguntaUno(models.Model):
    VALORES = (
        ('1', 'No es importante'),
        ('2', 'Algo importante'),
        ('3', 'Importante'),
        ('4', 'Muy importante'),
        ('5', 'No sabría responder'),
    )

    valor = models.CharField(
        max_length=1, choices=VALORES, verbose_name='Valor')
    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta 1: ¿Qué valor le otorga usted a la descentralización en la cotidianeidad y en la ' \
                       'calidad de vida de las personas?'
        unique_together = ('usuario',)


class PreguntaDos(models.Model):
    VALORACION = (
        (1, '1: Poco prioritario'),
        (2, '2: Algo prioritario'),
        (3, '3: Prioritario'),
        (4, '4: Muy prioritario'),
        (5, 'No sabría responder'),
    )

    propuesta_1 = models.IntegerField(verbose_name='Rendimiento de cuentas', choices=VALORACION,
                                     help_text='Que las autoridades elegidas directamente, rindan cuenta a la ciudadanía.')

    propuesta_2 = models.IntegerField(verbose_name='Acceso a bienes y prestación de servicios', choices=VALORACION,
                                     help_text='Que la ciudadanía tenga acceso a bienes y prestaciones de servicios públicos, que hoy entrega el gobierno central, a través de los gobiernos regionales y municipalidades.')

    propuesta_3 = models.IntegerField(verbose_name='Mayores recursos públicos', choices=VALORACION,
                                     help_text='Que los gobiernos regionales y municipalidades cuenten con mayores recursos financieros, y sus usos sean definidos en el territorio.')

    propuesta_4 = models.IntegerField(verbose_name='Más profesionales,', choices=VALORACION,
                                     help_text='Que los gobiernos regionales y municipalidades cuenten con más profesionales, para el cumplimiento de sus objetivos.')

    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta 2: Impacto de la descentralización en las personas y comunidades.'
        unique_together = ('usuario',)


class PreguntaTres(models.Model):
    ITEMS = (
        (1, 'Gobierno Regional'),
        (2, 'Municipalidad'),
        (3, 'Ambas'),
        (4, 'No sabría responder')
    )

    iniciativa_1 = models.IntegerField(verbose_name='Iniciativas ambientales', choices=ITEMS,
                                       help_text='Iniciativas ambientales')
    iniciativa_2 = models.IntegerField(verbose_name='Infraestructura pública', choices=ITEMS,
                                       help_text='Infraestructura pública')
    iniciativa_3 = models.IntegerField(verbose_name='Servicios o beneficios sociales', choices=ITEMS,
                                       help_text='Servicios o beneficios sociales')
    iniciativa_4 = models.IntegerField(verbose_name='Fomento productivo', choices=ITEMS,
                                       help_text='Fomento productivo')
    iniciativa_5 = models.IntegerField(verbose_name='Ordenamiento del territorio', choices=ITEMS,
                                       help_text='Ordenamiento del territorio')
    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta 3: Iniciativas que podrían ser incluidas dentro de la Política Nacional de ' \
                       'Descentralización.'
        unique_together = ('usuario',)


class OpcionesPreguntaCinco(models.Model):
    clave = models.CharField(max_length=2)
    texto = models.TextField()

    def __str__(self):
        return self.texto
    

class PreguntaCinco(models.Model):
    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)
    opciones = models.ManyToManyField(OpcionesPreguntaCinco, verbose_name='Selecciona tres opciones')

    class Meta:
        verbose_name = 'Pregunta 5: Para usted ¿cuáles de las siguientes medidas preferiría que fuesen implementadas por una Política de Descentralización de Chile? Marcar tres alternativas.'
        unique_together = ('usuario',)

    def get_opciones_texto(self):
        return [opcion.texto for opcion in self.opciones.all()]


class PreguntaSeis(models.Model):
    VALORES = (
        ('1', 'Mejorará la calidad de vida de las personas.'),
        ('2', 'Mantendrá de igual manera la calidad de vida de las personas.'),
        ('3', 'Generará un retroceso en la calidad de vida de las personas.'),
        ('4', 'No sabría responder'),
    )

    valor = models.CharField(
        max_length=1, choices=VALORES, verbose_name='Valor')
    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta 6: Considerando que una Política de Descentralización de Chile contaría con una agenda de trabajo con un plazo de implementación a 10 años, ¿con cuál de las siguientes alternativas usted está más de acuerdo?'
        unique_together = ('usuario',)


class PreguntaSiete(models.Model):
    texto_respuesta = models.CharField(max_length=200, blank=True, null=True)
    usuario = models.ForeignKey('users.User', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Pregunta 7: Para finalizar y considerando sus respuestas anteriores, ¿qué temática o medida agregaría, para serconsiderada en una Política de Descentralización de Chile? Esta pregunta es opcional.'
        unique_together = ('usuario',)

applications/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .functions import validar_rut
from .managers import UserManager
from applications.regioncomuna.models import Comuna



class User(AbstractBaseUser, PermissionsMixin):

    USER_GENRE_CHOICES = (
        ('', 'Elige una opción'),
        ('FEM', 'Femenino'),
        ('MASC', 'Masculino'),
        ('NOBIN', 'No binario'),
        ('OTRO', 'Otro'),
        ('PND', 'Prefiero no decirlo')
    )

    USER_PUEBLOS_CHOICES = (
        ('', 'Elige una opción'),
        ('NP', 'No pertenece'),
        ('AIM', 'Aimara'),
        ('ATAC', 'Atacameño'),
        ('COLL', 'Colla'),
        ('CHAN', 'Chango'),
        ('DIAG', 'Diaguita'),
        ('KAW', 'Kawésqar'),
        ('MAPU', 'Mapuche'),
        ('QUEC', 'Quechua'),
        ('RAPA', 'Rapa-Nui'),
        ('SELK', 'Selknam'),
        ('YAG', 'Yagán'),
        ('OTRO', 'Otro'),
    )

    USER_AGE_CHOICES = (
        ('', 'Elige una opción'),
        ('14-18', 'De 14 a 18 años'),
        ('19-25', 'De 19 a 25 años'),
        ('26-35', 'De 26 a 35 años'),
        ('36-45', 'De 36 a 45 años'),
        ('46-55', 'De 46 a 55 años'),
        ('56-65', 'De 56 a 65 años'),
        ('66-75', 'De 66 a 75 años'),
        ('75-120', '76 años o más'),
    )

    FAMILIARIDAD_CHOICES = (
        ("si", "Si"),
        ("no", "No")
    )

    rut = models.CharField(max_length=15, validators=[validar_rut], unique=True)
    password = models.CharField(max_length=200, blank=True)
    email = models.TextField(max_length=100, blank=True, null=True)
    genero = models.CharField(max_length=5, choices=USER_GENRE_CHOICES, blank=True, null=True)
    comuna = models.ForeignKey(Comuna, null=True, blank=True, verbose_name='Comuna', on_delete=models.SET_NULL)
    edad = models.CharField(choices=USER_AGE_CHOICES, blank=True, null=True)
    politica_privacidad = models.BooleanField(blank=True, null=True, default=False)
    encuesta_completada = models.BooleanField(default=False)
    fecha_encuesta_completada = models.DateTimeField(blank=True, null=True)
    recibir_resultados = models.BooleanField(default=False)
    pueblo_originario = models.CharField(max_length=5, choices=USER_PUEBLOS_CHOICES, blank=True, null=True)
    familiaridad = models.CharField(choices=FAMILIARIDAD_CHOICES, blank=True, null=True)

    #Setiando el nombre de usuario al rut
    USERNAME_FIELD = 'rut'    

    is_staff = models.BooleanField('Usuario administrador', default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

#    def save(self, *args, **kwargs):
#        # Formatear el RUT antes de guardar
#        rut_formateado = self.rut
#        self.rut = rut_formateado
#        super().save(*args, **kwargs)

templates/apps/surveys/datos_usuario_form.html
{% extends "base/base.html" %}
{% load static %}

{% block views %}

<section class="container">
    <div class="cols-12 my-0 mx-3">
    <div class="row justify-content-center">
            <div class="col-md-6 mx-md-auto">
                {% include "components/desentralizacion_banner.html" %}
            </div>
    
            <div class="col-12 col-md-12  col-lg-10 mx">
                <p class="font-level-1 text-center font-weight-bold ">Antes de empezar,<br
                    class="d-block d-md-none"> queremos saber
                    <br class="d-none d-sm-block d-md-none"> de tí:
                </p>
            </div>
            <div class="container-fluid">
            <div class="mx-2 mx-md-5">
                <div class="cols-12 row justify-content-center">
                    <form class="col-md-8 col-lg-5 col-xl-5" method="POST">
                        {% csrf_token %}
                        {{ form.non_field_errors }}
                        <div >
                            <label for="region">¿En qué región vives?</label>
                            <div class="input-group-prepend border border-2 border-accent rounded">
                                <select class="form-control" id="region" name="region">
                                    <option value="" class='text-muted'>Elige una opción</option>
                                    {% for region in regiones %}
                                    <option value="{{ region.id }}" {% if region_guardada == region %}selected{% endif %}>{{ region.region }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div id="region_error" style="color: red; display: none;">
                                Debes elegir una región antes de continuar.
                            </div>
                        </div>
                        <div class='my-3 my-md-4'>
                            {{ form.comuna.label_tag }}
                            {{ form.comuna }}
                            {{ form.comuna.errors }}
                        </div>
                        <div class='my-3 my-md-4'>
                            {{ form.genero.label_tag }}
                            {{ form.genero }}
                            {{ form.genero.errors }}
                        </div>
                        <div class='my-3 my-md-4'>
                            {{ form.edad.label_tag }}
                            {{ form.edad }}
                            {{ form.edad.errors }}
                        </div>
                        <div class='my-3 my-md-4'>
                            {{ form.pueblo_originario.label_tag }}
                            {{ form.pueblo_originario }}
                            {{ form.pueblo_originario.errors }}
                        </div>
                        <div class='my-3 my-md-4'>
                            {{ form.familiaridad.label_tag }}
                            {{ form.familiaridad }}
                            {{ form.familiaridad.errors }}
                        </div>
                        
                        
                        <div class="my-4 my-md-5">
                            <div class=" form-group my-3 my-md-5 ">
                                <div class='d-flex flex-row justify-content-start align-self-center '>
                                    {{ form.politica_privacidad }}
                                    <p>Leí y acepto la </p>&nbsp;
                                    <a href="{% url 'home_app:politicas_privacidad' %}" target="_blank"> Política de Privacidad.</a>
                                    {{ form.politica_privacidad.errors }}
                                </div>
                                <div class="my-2">
                                        <p class="font-level-6 font-weight-light">Continúa con la siguiente pregunta sobre:<br>
                                        <strong class="font-level-6">Valor de la Descentralización</strong></p>
                                        <button type="submit" class="btn btn-primary btn-lg btn-block text-nowrap"
                                            value="Submit">
                                            Siguiente
                                            <i class="material-symbols-outlined px-3 ">
                                                arrow_forward_ios
                                            </i>
                                        </button>
                                </div>
                        </div>
                    </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="my-3 col-md-12 mw-100 mx-0 px-0">
    {% include "components/logo_banner.html" %}
</div>

{% include "components/modal_salida_encuesta.html" %}

{% endblock views %}

{% block scripts %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    // Identificar todos los enlaces del navbar y footer
    $('nav a, footer a').on('click', function(e) {
      e.preventDefault();

      // Guardar el href del enlace en el botón de confirmación del modal
      $('#confirmExitButton').attr('href', $(this).attr('href'));

      // Mostrar el modal
      $('#exitSurveyModal').modal('show');
    });
  });
</script>

<script>
    $(document).ready(function ()
    {
        // Ocultar el campo de comuna al cargar la página si no hay comuna guardada
        {% if not comuna_guardada %}
            $('#id_comuna').parent().hide();
        {% endif %}

        $('#region').change(function ()
        {
            if ($(this).val() != '')
            {
                // Si se selecciona una región, mostrar el campo de comuna
                $('#id_comuna').parent().show();
            } else
            {
                // Si no se selecciona ninguna región, ocultar el campo de comuna
                $('#id_comuna').parent().hide();
            }
        });

        $('form').submit(function (e)
        {
            if ($('#region').val() == '')
            {
                // Si el campo de región está vacío cuando se intenta enviar el formulario, mostrar el mensaje de error y evitar que el formulario se envíe
                e.preventDefault();
                $('#region_error').show();
            }
        });
    });

    $('#region').change(function ()
    {
        var regionId = $(this).val();
        if (regionId != '')
        {
            $.getJSON('{% url "surveys_app:comunas_por_region" region_id=0 %}'.slice(0, -2) + regionId + '/', function (comunas)
            {
                var options = '<option value="">Selecciona una comuna</option>';
                for (var i = 0; i < comunas.length; i++)
                {
                    options += '<option value="' + comunas[ i ].id + '">' + comunas[ i ].comuna + '</option>';
                }
                $('#id_comuna').html(options);
                $('#id_comuna').parent().show();
            });
        } else
        {
            $('#id_comuna').parent().hide();
        }
    });

</script>

{% endblock scripts %}

templates/apps/surveys/pregunta_cinco.html
{% extends "base/base.html" %}
{% load static %}

{% block views %}
<section class="container">
  <div class="cols-12 my-0 mx-3">
    <div class="row justify-content-center">
      <div class="col-md-6 mx-md-auto my-2">
        {% include "components/desentralizacion_banner.html" %}
      </div>
      <div class="col-lg-9 d-flex justify-content-between my-2">
        <button type="button" class="btn btn-pill-primary text-nowrap"
          onclick="window.location.href='{% url 'surveys_app:pregunta_tres' %}'">
          <i class="material-symbols-outlined">chevron_left</i>
          Ir atrás
        </button>
        <button type="button" class="btn btn-pill-primary text-primary text-nowrap"
          onclick="window.location.href='{% url 'surveys_app:pregunta_seis' %}'">
          Siguiente<i class="material-symbols-outlined">chevron_right</i>
        </button>
      </div>

      <div class="col-lg-10">
        <p class="font-level-1 text-center my-3">Pregunta 4 de 6:</p>
      </div>
      <div class='col-lg-9 my-2 mx-1'>
        <p class="font-level-5 mx-2">¿Cuáles de las siguientes medidas preferirías que fuesen promovidas por una Política de Descentralización de Chile? Marcar tres alternativas.</p>
      </div>
      <div class="col-12 col-md-8 col-lg-9 mx-5 justify-content-center">
        <form method="post" class="form col-12" action="{% url 'surveys_app:pregunta_cinco' %}" onsubmit="return validateForm()">
          {% csrf_token %}
          
          {% for choice in opciones %}
            <div class="d-flex">
              <button class="btn-option text-primary font-level-5 px-0 btn-lg my-3 w-100
                {% if choice.id in initial_opciones %}selected active{% endif %}"
                type="button" value="{{ choice.id }}" style="background-color: white;"
                onclick="toggleSelection(this)">
                {{ choice.texto|safe }}
                <img src="{% static 'img/checkbox.svg' %}" class="align-self-end-end ml-5" 
                  id="img_{{ choice.id }}"
                  {% if choice.id in initial_opciones %}style="display: inline-block;"{% else %}style="display: none;"{% endif %} />
              </button>
            </div>
          {% endfor %}

          <!-- Campo oculto para almacenar los valores seleccionados -->
          <input type="hidden" id="id_opciones" name="opciones" value="{{ initial_opciones|join:',' }}">

          <!-- Muestra errores del campo valor -->
          {% if form.non_field_errors %}
            <p>{{ form.non_field_errors }}</p>
          {% endif %}

          <!-- Botón para el envío del formulario completo -->
          <div class="col-md-9 mx-md-auto my-4 px-0">
            <p class="font-level-6 font-weight-light">Continúa con la siguiente pregunta sobre:
              <br><strong class="font-level-6">Tu opinión sobre la Descentralización</strong>
            </p>
            <button type="submit" id="enviar_button" class="btn btn-primary btn-lg btn-block">
              Siguiente <i class="material-symbols-outlined px-3">arrow_forward_ios</i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<div class="my-3 col-md-12 mw-100 mx-0 px-0">
  {% include "components/logo_banner.html" %}
</div>

{% include "components/modal_salida_encuesta.html" %}

{% endblock views %}

{% block scripts %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    // Identificar todos los enlaces del navbar y footer
    $('nav a, footer a').on('click', function(e) {
      e.preventDefault();
      // Guardar el href del enlace en el botón de confirmación del modal
      $('#confirmExitButton').attr('href', $(this).attr('href'));
      // Mostrar el modal
      $('#exitSurveyModal').modal('show');
    });
  });

  function toggleSelection(button) {
    let selectedButtons = document.querySelectorAll('.selected');
    // Verifica si ya hay tres opciones seleccionadas
    if (selectedButtons.length >= 3 && !button.classList.contains('selected')) {
      // Si ya hay tres opciones seleccionadas y se hace clic en una no seleccionada,
      // deselecciona la primera opción seleccionada
      let firstSelectedButton = selectedButtons[0];
      firstSelectedButton.classList.remove('selected');
      firstSelectedButton.classList.remove('active');
      let firstImageId = "img_" + firstSelectedButton.value;
      let firstImage = document.getElementById(firstImageId);
      firstImage.style.display = "none";
    }
    // Cambia el estado de selección del botón clicado
    button.classList.toggle('selected');
    button.classList.toggle('active'); // Agrega o elimina la clase 'active'
    let imageId = "img_" + button.value;
    let image = document.getElementById(imageId);
    image.style.display = button.classList.contains('selected') ? "inline-block" : "none";
    
    // Actualiza el valor del campo oculto
    let selectedValues = [...document.querySelectorAll('.selected')].map(btn => btn.value).join(',');
    document.getElementById('id_opciones').value = selectedValues;
    console.log("Selected values:", selectedValues);  // Debug statement
  }

  function validateForm() {
    let selectedValues = document.getElementById('id_opciones').value;
    if (selectedValues.split(',').length !== 3) {
      alert("Debe seleccionar exactamente tres opciones.");
      return false;
    }
    return true;
  }
</script>

{% endblock scripts %}

templates/apps/surveys/pregunta_seis.html
{% extends "base/base.html" %}
{% load static %}
{% block views %}
<section class="container">
  <div class="cols-12 my-0 mx-3">
    <div class="row justify-content-center">
      <div class="col-md-6 mx-md-auto my-2">
        {% include "components/desentralizacion_banner.html" %}
      </div>

      <div class="col-lg-9 d-flex justify-content-between my-2">
        <button type="radio" class=" btn btn-pill-primary text-primary text-nowrap active"
          onclick="window.location.href='{% url 'surveys_app:pregunta_cinco' %}'"><i
            class="material-symbols-outlined">
            chevron_left
          </i>
          Ir atrás</button>
          <button type="button" class="btn btn-pill-primary text-primary text-nowrap"
            onclick="window.location.href='{% url 'surveys_app:pregunta_siete' %}'">Siguiente <i
              class="material-symbols-outlined">
              chevron_right
            </i></button>
      </div>

      <div class="col-lg-10">
        <p class=" font-level-1  text-center my-3">Pregunta 5 de 6:</p>

        <p class="font-level-5 text-justify mx-2 mx-md-5">Crees que una Política de Descentralización con un horizonte de 10 años...</p>
        <p class="font-level-5 text-justify mx-2 mx-md-5">Selecciona una de las siguientes alternativas.</p>
      </div>
      <div class="col-12 col-md-6 col-lg-6 mx-5 my-2 justify-content-center">

        <form id="pregunta-seis-form" method="post" action="{% url 'surveys_app:pregunta_seis' %}">
          {% csrf_token %}

          <!-- Muestra input para el formulario -->
          {% for choice in form.valor.field.choices %}
              <div class="d-flex">
                  <button class="btn-question px-0 btn-lg my-3 w-100 {% if valor_guardado == choice.0 %}selected active{% endif %}"
                      type="button" id="valor" value="{{ choice.0 }}"
                      onclick="document.getElementById('id_valor').value = '{{ choice.0 }}'; toggleImage(this);">
                      {{ choice.1 }}
                      <img src="{% static 'img/checkbox.svg' %}" class="align-self-end-end ml-5" id="img_{{ choice.0 }}"
                          {% if valor_guardado == choice.0 %}style="display: inline-block;"{% else %}style="display: none;"{% endif %} />
                  </button>
              </div>
          {% endfor %}


          <!-- Muestra errores del campo valor -->
          {% if form.non_field_errors %}
          <!-- Muestra el mensaje de error específico -->
          <p>{{ form.non_field_errors }}</p>
          {% endif %}

          <!-- Campo oculto para almacenar el valor seleccionado -->
          <input type="hidden" id="id_valor" name="valor" value="{{ valor_guardado }}">

          <!-- Botón para el envío del formulario completo -->
          <div class="col-md-9 mx-md-auto my-4 px-0">
            <p class="font-level-6 font-weight-light">Continúa con la siguiente pregunta sobre:<br><strong class="font-level-6">Impacto de la
              Descentralización</strong></p>
            <button type="submit" id="enviar_button" class="btn btn-primary btn-lg btn-block">Siguiente <i class="material-symbols-outlined px-3">
                arrow_forward_ios
              </i></button>
          </div>

        </form>
      </div>
    </div>
  </div>
</section>
<div class="my-3 col-md-12 mw-100 mx-0 px-0">
  {% include "components/logo_banner.html" %}
</div>

{% include "components/modal_salida_encuesta.html" %}

{% endblock views %}

{% block scripts %}

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script>
  $(document).ready(function() {
    // Identificar todos los enlaces del navbar y footer
    $('nav a, footer a').on('click', function(e) {
      e.preventDefault();

      // Guardar el href del enlace en el botón de confirmación del modal
      $('#confirmExitButton').attr('href', $(this).attr('href'));

      // Mostrar el modal
      $('#exitSurveyModal').modal('show');
    });
  });

</script>

<script>
  function toggleImage(button) {
    let imageId = "img_" + button.value;
    let image = document.getElementById(imageId);
    if (image.style.display === "none") {
      image.style.display = "inline-block";
    } else {
      image.style.display = "none";
    }
  }

  window.addEventListener('DOMContentLoaded', (event) => {
    let valorGuardado = '{{ valor_guardado }}';
    if (valorGuardado) {
      let btns = document.querySelectorAll('#valor');
      btns.forEach(function (btn) {
        if (btn.textContent == valorGuardado) {
          btn.classList.add('selected');
          btn.classList.add('active'); // Agrega la clase 'active'
          document.getElementById('id_valor').value = btn.value;
          let imageId = "img_" + btn.value;
          let image = document.getElementById(imageId);
          image.style.display = "inline-block";
        }
      });
    }
  });

  document.querySelectorAll('#valor').forEach(function (element) {
    element.addEventListener('click', function (event) {
      // Comprueba si el botón ya está seleccionado
      if (!event.target.classList.contains('selected')) {
        document.querySelectorAll('#valor').forEach(function (otherElement) {
          otherElement.classList.remove('selected');
          otherElement.classList.remove('active'); // Elimina la clase 'active' de todos los botones

          let imageId = "img_" + otherElement.value;
          let image = document.getElementById(imageId);
          image.style.display = "none";
        });
        event.target.classList.add('selected');
        event.target.classList.add('active'); // Agrega la clase 'active' al botón seleccionado
        document.getElementById('id_valor').value = event.target.value;

        let imageId = "img_" + event.target.value;
        let image = document.getElementById(imageId);
        image.style.display = "inline-block";
      }
    });
  });
  </script>

{% endblock scripts %}