applications/claveunica/urls.py
from django.urls import path
from .views import keycloak_login, keycloak_callback, keycloak_logout

app_name = 'claveunica'

urlpatterns = [
    path('keycloak_login/', keycloak_login, name='keycloak_login'),
    path('callback/', keycloak_callback, name='keycloak_callback'),
    path('keycloak_logout/', keycloak_logout, name='keycloak_logout'),
]

applications/home/urls.py
from django.urls import path
from .views import generar_reporte_completo

from . import views

app_name = 'home_app'

urlpatterns = [
    path(
        '',
        views.HomePageView.as_view(),
        name='index',
        ),

     path(
        'proceso-participativo',
        views.ProcesoParticipativoView.as_view(),
        name='proceso_participativo',
        ),

     path(
        'preguntas-frecuentes',
        views.PreguntasFrecuentesView.as_view(),
        name='preguntas_frecuentes',
        ),

    path(
        'documentos/',
        views.DocumentosView.as_view(),
        name='documentos',
        ),

    path(
        'politicas-privacidad',
        views.PoliticasPrivacidadView.as_view(),
        name='politicas_privacidad',
        ),

    path(
        'onboarding',
        views.OnboardingView.as_view(),
        name='onboarding',
    ),

    path(
        'descentralizacion_para_bienestar',
        views.DescentralizacionBienestarView.as_view(),
        name='descentralizacion-bienestar',
    ),
    path(
        'consejo_asesor',
        views.ConsejoAsesorListView.as_view(),
        name='consejo-asesor',
    ),
    path(
        'calendario_dialogos',
        views.CalendarioDialogosView.as_view(),
        name='calendario_dialogos',
    ),
     path(
         'generar_reporte_completo/', 
         generar_reporte_completo, 
         name='generar_reporte_completo'
    ),

]

applications/noticiasymedia/urls.py
from django.urls import path

from . import views
from .views import  NoticiaDetailView, LatestAlbumsByRegionView, AlbumsByRegionView, FileFieldFormView

app_name = 'noticiasymedia_app'

urlpatterns = [
    path('noticias/', views.NoticiasView.as_view(), name='noticias'),
    path('multimedia/', views.MultimediaView.as_view(), name='multimedia'),
    path('noticias/<slug>/', NoticiaDetailView.as_view(), name='noticia_detail'),
    path('multimedia/<slug>/', views.MultimediaDetailView.as_view(), name='multimedia_detail'),
    path('fotos/', LatestAlbumsByRegionView.as_view(), name='albums'),
    path('fotos/<int:region_id>/', AlbumsByRegionView.as_view(), name='albums_by_region'),
    path('upload_photos/', FileFieldFormView.as_view(), name='upload_photos'),
]

hablemosdedescentralizacion/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from applications.home.admin import admin_site 

#urls errores 
from django.conf.urls import handler404 , handler500 
from applications.home.views import Error404 , Error500 , Error503


urlpatterns = [
    path('admin/', admin_site.urls),
    re_path('', include('applications.users.urls')),
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.surveys.urls')),
    re_path('', include('applications.claveunica.urls')),
    re_path('', include('applications.noticiasymedia.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404.as_view()

handler500 = Error500.as_error_view()

urlpatterns += [
path('503/', Error503.as_error_view(), name='error_503'),
]

templates/components/boton-scroll.html
{% load static %}

<div id="button-top" class="button-top d-flex justify-content-end mx-4 mb-4 d-none d-block d-md-none">
  <a class="btn btn-outline-primary btn-lg">Volver Arriba <i class="material-symbols-outlined ml-3">keyboard_double_arrow_up</i></a>
</div>

{% block scripts %}
<script>
document.addEventListener("DOMContentLoaded", function() {
  var buttonTop = document.getElementById("button-top");
  var scrollCount = 0;

  // Mostrar el botón cuando el usuario haya realizado scroll dos veces
  window.addEventListener("scroll", function() {
    if (window.scrollY > window.innerHeight) {
      scrollCount++;
      if (scrollCount >= 2) {
        buttonTop.classList.add("show");
      }
    } else {
      buttonTop.classList.remove("show");
    }
  });

  // Hacer scroll suave cuando se hace clic en el botón
  buttonTop.addEventListener("click", function() {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
});
</script>
{% endblock %}

templates/components/card_foto.html
{% load static %}
{% block content %}
{% for album in albums %}
<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4  d-flex justify-content-center">
  <div class="card-s my-2 justify-content-between">
    <div class="">
      <div class="card-img">
        <img class="img-portada" src="{{ album.foto_portada.url }}" alt="img-miniatura" />
      </div>
      <div class="d-flex justify-content-between py-0">
        <p class="font-level-8 m-0 mb-2">
          <strong> Última actualización:</strong> {{ album.modified|date:"l j \\d\\e F \\d\\e Y" }}
        </p>
      </div>
      <div class="body">
        <p class="h3 text-decoration-underline"><u>Diálogo regional {{ album.region }}</u></p>
      </div>
    </div>
    <div class="container d-flex justify-content-end px-0 mt-1">
      <a class="btn-card-s" href="{% url 'noticiasymedia_app:albums_by_region' album.region.id %}">Ver más ></a>
    </div>
    
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/components/card_noticia.html
{% load static %}
{% block content %}
{% for noticia in noticias %}
<div class="col-12 col-sm-12 col-md-6 col-lg-6 col-xl-4  d-flex justify-content-center">
  <div class="card my-2">
    <div>
    <div class="card-img">
      <img class="img-portada" src="{{ noticia.portada_noticia.url }}" alt="img-miniatura" />
    </div>
    <div class="d-flex justify-content-between  py-0">
      <p class="font-level-8 m-0">
      <strong> Fecha de publicación:</strong> {{ noticia.created|date:"l j \\d\\e F \\d\\e Y" }}
    </p>
    </div>
    <div class="body">
      <p class="h3 text-decoration-underline"><u>{{ noticia.titulo_noticia }}</u></p>
      <p class="description-card font-base text-left">{{ noticia.bajada_noticia }}</p>
      <div class="tags row">
        {% for tag in noticia.tag.all %}
        <div class="col-auto pb-2">
          <div class="badge border border-primary font-level-7">{{ tag.tag }}</div>
        </div>
        {% endfor %}
      </div>
    </div>
    </div>
    <a class="btn-more" href="{% url 'noticiasymedia_app:noticia_detail' noticia.slug %}">Ver más ></a>
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/components/carrusel_fotos.html
{% load static %}
{% block content %}
<div class="container-fluid">
<div id="carouselNoticiasIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    {% for album in latest_albums|slice:3 %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <div class="card-carrusel-fotos">
        <div>
          <div class="card-img">
            <img class="img-portada img-small img-fluid" src="{{ album.foto_portada.url }}" alt="img-miniatura" />
          </div>
          <div class="d-flex justify-content-between  py-0">
            <p class="font-level-8 m-0">
              <strong> Última actualización: </strong> {{ album.modified|date:"l j \\d\\e F \\d\\e Y" }}
            </p>
          </div>
          <div class="body">
            <p class="h3 text-decoration-underline"><u>Diálogo regional de la {{ album.region }}</u></p>
          </div>
        </div>
        <a class="btn-more" href="{% url 'noticiasymedia_app:albums_by_region' album.region.id %}">Ver más ></a>
      </div>
    </div>
    {% endfor %}
  </div>
  <ol  class="carousel-indicators carousel-indicators-custom ">
    {% for album in albums|slice:"-3:" %}
    <li data-target="#carouselNoticiasIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %} active {% endif %}></li>
    {% endfor %}
  </ol>
</div>
</div>
{% endblock content %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script>
  function initCarouselForSmallScreens() {
    if ($(window).width() <= 768) {
      $('.carousel').carousel({
        interval: 1500
      });
    }
  }

</script>

{% endblock%}

templates/components/carrusel_noticias.html
{% load static %}
{% block content %}
<div class="container-fluid">
<div id="carouselNoticiasIndicators" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    {% for noticia in noticias|slice:"-3:" %}
    <div class="carousel-item {% if forloop.first %} active {% endif %}">
      <div class="card">
        <div>
        <div class="card-img">
          <img class="img-portada img-small img-fluid" src="{{ noticia.portada_noticia.url }}" alt="img-miniatura" />
        </div>
        <div class="d-flex justify-content-between  py-0">
          <p class="font-level-8 m-0">
          <strong> Fecha de publicación:</strong> {{ noticia.created|date:"l j \\d\\e F \\d\\e Y" }}
        </p>
        </div>
        <div class="body">
          <p class="h3 text-decoration-underline"><u>{{ noticia.titulo_noticia }}</u></p>
          <p class="description-card font-base text-left">{{ noticia.bajada_noticia }}</p>
          <div class="tags row">
            {% for tag in noticia.tag.all %}
            <div class="col-auto pb-2">
              <div class="badge border border-primary font-level-7">{{ tag.tag }}</div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
        <a class="btn-more" href="{% url 'noticiasymedia_app:noticia_detail' noticia.slug %}">Leer ></a>
      </div>
      </div>
      {% endfor %}
    </div>
    <ol  class="carousel-indicators carousel-indicators-custom ">
      {% for noticia in noticias|slice:"-3:" %}
      <li data-target="#carouselNoticiasIndicators" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %} active {% endif %}></li>
      {% endfor %}
    </ol>
</div>
</div>
{% endblock content %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script>
  function initCarouselForSmallScreens() {
    if ($(window).width() <= 768) {
      $('.carousel').carousel({
        interval: 1500
      });
    }
  }

</script>

{% endblock%}

templates/components/colapsable.html
{% load static %}
<div class="card-data-list card-data-list-flush m-4 bg-gray-200">
<ol class="list-unstyled w-100" id="collapsibleFlushAccordion{{ forloop.parentloop.counter }}">
  <li>
    <button class="btn text-left w-100 d-flex align-items-start justify-content-between py-4 px-3" id="collapsibleFlushHeading{{ forloop.counter }}" type="button" data-toggle="collapse" data-target="#collapsibleFlushCollapse{{ forloop.counter }}" aria-controls="collapsibleFlushCollapse{{ forloop.counter }}" aria-expanded="false">
    <span class="font-level-3 mb-0">{{ titulo }}</span>
    <span class="toggler-icon cl cl-m-arrow-down cl-2x" aria-hidden="true"></span>
  </button>
    <div class="collapse" id="collapsibleFlushCollapse{{ forloop.counter }}" aria-labelledby="collapsibleFlushHeading{{ forloop.counter }}" data-parent="#collapsibleFlushAccordion{{ forloop.parentloop.counter }}">
      <div class="pr-5 pb-3 pl-3 pt-3 border-top border-gray-b">
        <p class="h4">
          {{ contenido|linebreaksbr }}
        </p>
      </div>
    </div>
  </li>
</ol>
</div>

templates/components/desentralizacion_banner.html
{% load static %}
<div class=" col mw-75 d-flex flex-column justify-content-center align-items-center">

  <img src="{% static 'img/logo_descentralizacion.svg' %}" class="w-75 mx-5 img-fluid" alt="logo-descentralizacion" />

</div>

templates/components/footer.html
{% load static %}

<footer class="content-always-on-display">
  <div class="container-fluid">
    <div class="row">
      <!-- aqui esta la linea -->
      <div class="deco-line ">
        <div class="azul"></div>
        <div class="rojo"></div>
      </div>
      <div class="col-md-3 a11y-fonts-col-12">
          <img src="{%  static 'img/logo-subdere-blanco.svg' %}" class="w-75 ml-md-4"/>
      </div>

      <div class="col-md-4 m-2 ml-4 a11y-fonts-col-12">
        <div class="mb-2 ">Secciones</div>
        <a href="{% url 'home_app:index' %}">Inicio</a>
        <a href="{% url 'home_app:proceso_participativo' %}">Proceso Participativo </a>
        <a href="{% url 'home_app:preguntas_frecuentes' %}">Preguntas Frecuentes </a>
        <a href="">Historia de la Descentralización</a>
        <a href="{% url 'home_app:documentos' %}">Documentos</a>
        <a href="{% url 'noticiasymedia_app:noticias' %}">Noticias</a>
        <a href="{% url 'noticiasymedia_app:multimedia' %}">Videos</a>
      </div>

      <div class="ml-4 d-block d-md-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="303" height="2" viewBox="0 0 303 2" fill="none">
          <path d="M0 1.31836H302.058" stroke="white"/>
        </svg>
      </div>
      <div class="col-md-4 m-sm-1 ml-lg-4 a11y-fonts-col-12">
        <div class="mb-2">¿Necesitas ayuda? <br class="d-sm-block d-lg-none">Escríbenos a:</div>
        <div>
        <p class="py-0 my-0 text-underline m-0" id="email-link" data-toggle="tooltip" data-placement="bottom" title="Haz clic para copiar" style="cursor: pointer;">descentralizacion@subdere.gov.cl</p>
        </div>
        <p class="d-block mt-5 font-base">
          Teatinos 92 - Pisos 2 y 3. Santiago,
        </p>
        <p class="d-block mt-3 font-base">Chile</p>
        <a class="py-0" href="{% url 'home_app:politicas_privacidad' %}">Politicas de Seguridad</a>
      </div>
    </div>
  </div>
</footer>

{% block scripts %}
    <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap 4 (popper.js es requerido por los tooltips de Bootstrap) -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

  <script>
    $(document).ready(function() {
      // Inicializar los tooltips usando Bootstrap 4
      $('[data-toggle="tooltip"]').tooltip({
        // Restablecer el título del tooltip cuando se oculta
        hide: function (event, ui) {
          $(this).attr('data-original-title', 'Haz clic para copiar');
        }
      });
  
      // Función para copiar el correo al portapapeles
      function copyToClipboard(text) {
        var dummy = document.createElement("textarea");
        document.body.appendChild(dummy);
        dummy.value = text;
        dummy.select();
        document.execCommand("copy");
        document.body.removeChild(dummy);
      }
  
      // Agregar evento clic al enlace
      $("#email-link").click(function() {
        var email = $(this).text(); // Obtener el correo electrónico del enlace
        copyToClipboard(email); // Copiar al portapapeles
      
        // Mostrar el tooltip usando Bootstrap 4
        $(this).attr('data-original-title', 'Correo copiado con éxito!').tooltip('show').addClass('custom-tooltip');
      
        // Ocultar el tooltip después de 2 segundos
        setTimeout(function() {
          $("#email-link").tooltip("hide");
        }, 2000);
      });
    });
  </script>
  
{% endblock %}

templates/components/invitacion.html
{% load static %}
<div class="container col-md-12 mt-5"> 
   <p class="font-level-2 text-center pb-4 text-black font-weight-bold">Consulta Ciudadana</p>
   <p class="h4 pb-4">Se realizará una consulta a la ciudadanía, online y con Clave Única, que busca recoger las opiniones y 
    aportes de personas que deseen participar en la elaboración de la Política de Descentralización de Chile.</p>

    <div class="my-3 d-flex flex-column align-items-center">
            <button class="btn btn-neutral btn-default-size text-white border-white bg-primary mb-4" type="button" onclick="window.location.href='/onboarding'">Participar
                <i class="material-symbols-outlined">
                chevron_right
                </i>
            </button>
    </div>   
</div>

templates/components/logo_banner.html
{% load static %}
<div class="container mb-5">
    <div class="row justify-content-md-center">
        <div class="col-12">
            <img src="{% static 'img/icono-patron.svg' %}" class="mw-100 img-fluid" alt="patron con iconos de colores" />
        </div>
    </div>
</div>

templates/components/navbar.html
{% load static %}
<nav id="navbar" class="navbar navbar-light navbar-expand-lg navbar-lg navbar-lines ">
  <div class="cols-12-extended column ml-3  mr-5 ">
    <a class="navbar-brand " href="/">
      <div class="blue"></div>
      <div class="red"></div>
      <p class="font-level-6 font-weight-bold mt-2">
        Subsecretaría de <br class="d-xl-none d-block"> Desarrollo <br class="d-none d-sm-none d-lg-block"> Regional y<br class="d-xl-none d-none"> <br  class="d-sm-none d-md-block"> Administrativo
      </p>
    </a>
    <div class="toolbar align-items-end my-2 d-sm-block d-lg-none">
      <a class="toolbar-btn toolbar-behavior-contrast" href="#"><i class="cl cl-contrast"></i></a>
      <div class="toolbar-btn-group">
        <a class="toolbar-btn toolbar-behavior-decrease" href="#"><i class="cl cl-decrease-text"></i></a>
        <a class="toolbar-btn toolbar-behavior-increase" href="#"><i class="cl cl-increase-text"></i></a>
      </div>
      <a class="toolbar-btn toolbar-toggler ml-1" href="#"><i class="cl cl-accessibility toolbar-behavior-on"></i><span class="toolbar-behavior-off">X</span></a>
    </div>
  </div>
  <button class="navbar-toggler collapsed text-gray-600" type="button" data-toggle="collapse" data-target="#navbarLightExampleCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <u>Menú</u>
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse"  id="navbarLightExampleCollapse">
    <ul class="navbar-nav mx-lg-5 my-lg-3 mx-lg-4 ">
      <div class="toolbar mx-3 d-none d-lg-block">
        <a class="toolbar-btn toolbar-behavior-contrast" href="#"><i class="cl cl-contrast"></i></a>
        <div class="toolbar-btn-group">
          <a class="toolbar-btn toolbar-behavior-decrease" href="#"><i class="cl cl-decrease-text"></i></a>
          <a class="toolbar-btn toolbar-behavior-increase" href="#"><i class="cl cl-increase-text"></i></a>
        </div>
        <a class="toolbar-btn toolbar-toggler ml-1" href="#"><i class="cl cl-accessibility toolbar-behavior-on"></i><span class="toolbar-behavior-off">X</span></a>
      </div> 
      <li class="nav-item">
        {% if user.is_authenticated %}
        <li class="nav-item "><a class="btn btn-lg btn-block btn-outline-danger btn-cerrar-sesion " href="{% url 'claveunica:keycloak_logout' %}">Cerrar sesión</a></li>
        {% else %}
        <form method="GET" class="nav-item ml-sm-3" action="{% url 'claveunica:keycloak_login' %}">
          <input id="next-url" type="hidden" name="next" value="">
          <button class="btn  ml-3 ml-sm-0 ml-md-0 pl-2  pl-md-0 btn-lg btn-block  btn-primary" id="btn-clave" type="submit" onclick="setNextUrl()">
            <div class="doc-icon m-2"><span class="cl cl-claveunica"></span></div>
            Iniciar sesión
          </button>
        </form>
        {% endif %}
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'home_app:generar_reporte_completo' %}">Descargar Reporte</a>
      </li>
      {% endif %}
    </ul>
    <ul class="navbar-nav justify-content-lg-start  my-2">      
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:index' %}">Inicio</a></li>
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:proceso_participativo' %}">Proceso Participativo</a></li>
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:calendario_dialogos' %}">Calendario de Diálogos Regionales</a></li>
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:preguntas_frecuentes' %}">Preguntas Frecuentes</a></li>
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:descentralizacion-bienestar' %}">Descentralización para el Bienestar</a></li>
      <li class="nav-item"><a class="nav-link font-level-6" href="{% url 'home_app:consejo-asesor' %}">Consejo Asesor</a></li>
      <div class="dropdown mr-lg-5 my-2">
        <a class="dropdown-toggle ml-2 pl-2 mt-4 font-level-6" id="navbarLinesLightExampleDropdown"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Publicaciones</a>
        <div class="dropdown-menu border-0 " aria-labelledby="dropdown">
          <a class="nav-item btn btn-drop font-level-6 " id="item-drop1" href="{% url 'home_app:documentos' %}">Documentación</a>
          <a class="nav-item btn btn-drop font-level-6 " id="item-drop2" href="{% url 'noticiasymedia_app:noticias' %}">Noticias</a></a>
          <a class="nav-item btn btn-drop font-level-6 " id="item-drop3"  href="{% url 'noticiasymedia_app:multimedia' %}">Videos</a></a>
          <a class="nav-item btn btn-drop font-level-6 " id="item-drop3"  href="{% url 'noticiasymedia_app:albums' %}">Fotos</a></a>
      </div>
    </div>
    </ul>
  </div>
</nav>
{% block scripts%}
<script>
  
  // Encuentra todos los elementos con la clase 'btn'
let buttons = document.querySelectorAll('.btn-drop');

// Aplica los estilos a cada botón
buttons.forEach((btn) => {
  // Estilo base
  btn.style.color = "#001C41";
  btn.style.backgroundColor = "#CFE1F3";
  btn.style.fontsize= "16px";
  btn.style.fontweight="400"; 
  btn.style.textDecoration = "underline";
  
  // Estilo para :focus
  btn.addEventListener('focus', function() {
    this.style.fontWeight = "bold";
    this.style.textDecoration = "underline";
  });

  // Estilo para :hover
  btn.addEventListener('mouseover', function() {
    this.style.fontWeight = "bold";
    this.style.textDecoration = "underline";
  });

  // Estilo para :active
  btn.addEventListener('mousedown', function() {
    this.style.fontWeight = "bold";
    this.style.border = "2px solid #3F87D0";
    this.style.textDecoration = "underline";
  });

  // Estilo para cuando el botón se desenfoca o el mouse se aleja
  btn.addEventListener('blur', function() {
    this.style.fontWeight = "normal";
    this.style.textDecoration = "none";
  });
  btn.addEventListener('mouseout', function() {
    this.style.outline = "";
    this.style.border = "";
    this.style.fontWeight = "normal";
    this.style.textDecoration = "underline";
  });
});
</script>
{% endblock %}

templates/components/row_noticias.html
{% load static %}
{% block content %}
{% for noticia in noticias|slice:"-3:" %}
<div class="col-4">
  <div class="card w-100 my-2 ">
    <div class="card-img">
      <img class="img-portada" src="{{ noticia.portada_noticia.url }}" alt="img-miniatura" />
    </div>
    <div class="d-flex justify-content-between  py-0">
      <p class="font-level-8 m-0">
      <strong> Fecha de publicación:</strong> {{ noticia.created|date:"l j \\d\\e F \\d\\e Y" }}
    </p>
    </div>
    <div class="body">
      <p class="h3 text-decoration-underline"><u>{{ noticia.titulo_noticia }}</u></p>
      <p class="description-card font-base text-left">{{ noticia.bajada_noticia }}</p>
      <div class="tags row">
        {% for tag in noticia.tag.all %}
        <div class="col-auto pb-2">
          <div class="badge border border-primary font-level-7">{{ tag.tag }}</div>
        </div>
        {% endfor %}
      </div>
    </div>
    <a class="btn-more" href="{% url 'noticiasymedia_app:noticia_detail' noticia.slug %}">Leer ></a>
  </div>
</div>
{% endfor %}
{% endblock content %}

templates/components/upload_photos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Subir Fotos</title>
    <link rel="stylesheet" href="{% static 'admin/css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'admin/css/widgets.css' %}">
</head>
<body>
    <h1>Subir Fotos</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Subir</button>
    </form>
</body>
</html>